#ifndef __MEMORYMAP_H__
#define __MEMORYMAP_H__

/* STACK ADDRESSES */
#define INST_ADDR_START     0
#define USRSYS_STACK_START  0x00100000 // ~ 0x002FFFFF 2MB
#define SVC_STACK_START     0x00300000 // ~ 0x003FFFFF 1MB
#define IRQ_STACK_START     0x00400000 // ~ 0x004FFFFF 1MB
#define FIQ_STACK_START     0x00500000 // ~ 0x005FFFFF 1MB
#define ABT_STACK_START     0x00600000 // ~ 0x006FFFFF 1MB
#define UND_STACK_START     0x00700000 // ~ 0x007FFFFF 1MB
#define TASK_STACK_START    0x00800000 // ~ 0x047FFFFF 64MB
#define GLOBAL_ADDR_START   0x04800000 // ~ 0x048FFFFF 1MB
#define DALLOC_ADDR_START   0x04900000 // ~ 0x07FFFFFF 55MB

/* STACK SIZE */
#define INSTMEM_SIZE        (USRSYS_STACK_START - INST_ADDR_START) 
#define USRSYS_STACK_SIZE   (SVC_STACK_START - USRSYS_STACK_START)
#define SVC_STACK_SIZE      (IRQ_STACK_START - SVC_STACK_START)
#define IRQ_STACK_SIZE      (FIQ_STACK_START - IRQ_STACK_START)
#define FIQ_STACK_SIZE      (ABT_STACK_START - FIQ_STACK_START)
#define ABT_STACK_SIZE      (UND_STACK_START - ABT_STACK_START)
#define UND_STACK_SIZE      (TASK_STACK_START - UND_STACK_START)
#define TASK_STACK_SIZE     (GLOBAL_ADDR_START - TASK_STACK_START)
#define GLOBAL_MEM_SIZE     (DALLOC_ADDR_START - GLOBAL_ADDR_START)
#define DALLOC_MEM_SIZE     (55 * 1024 * 1024)

/* STACK TOP */
/*
 * -4 is just for padding,
 * actually you don't need to subtract 4 from TOP(=START + SIZE)
 */
#define USRSYS_STACK_TOP    (USRSYS_STACK_START + USRSYS_STACK_SIZE - 4)
#define SVC_STACK_TOP    (SVC_STACK_START + SVC_STACK_SIZE - 4)
#define IRQ_STACK_TOP    (IRQ_STACK_START + IRQ_STACK_SIZE - 4)
#define FIQ_STACK_TOP    (FIQ_STACK_START + FIQ_STACK_SIZE - 4)
#define ABT_STACK_TOP    (ABT_STACK_START + ABT_STACK_SIZE - 4)
#define UND_STACK_TOP    (UND_STACK_START + UND_STACK_SIZE - 4)

#endif

